default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)
  base_path: !expr file.path(getwd(), "app", "data", "shared")
  data_path: !expr file.path(getwd(), "app", "data")
  executor: "docker"

dev:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "DEBUG")

local_docker:
  base_path: !expr Sys.getenv("BASE_PATH")
  data_path: !expr Sys.getenv("DATA_PATH")
  host_base_path: !expr Sys.getenv("HOST_BASE_PATH")
  executor: "docker"

prod:
  base_path: !expr Sys.getenv("BASE_PATH")
  data_path: !expr Sys.getenv("DATA_PATH")
  executor: "docker"

k8s:
  base_path: !expr Sys.getenv("BASE_PATH")
  data_path: !expr Sys.getenv("DATA_PATH")
  api_url: !expr Sys.getenv("KUBERNETES_API_URL")
  namespace: !expr Sys.getenv("KUBERNETES_NAMESPACE")
  token: !expr Sys.getenv("KUBERNETES_API_TOKEN")
  shinyproxy_id: !expr Sys.getenv("SHINYPROXY_ID")
  executor: "k8s"

