default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)
  base_path: !expr file.path(getwd(), "app", "data", "shared")
  data_path: !expr file.path(getwd(), "app", "data")
  script_path: !expr file.path(getwd(), "app", "data", "honeybee", "scripts")
  r_path: !expr file.path(getwd(), "app", "data", "honeybee", "R")
  executor: "docker"

dev:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "DEBUG")

prod:
  base_path: !expr Sys.getenv("BASE_PATH")
  data_path: !expr Sys.getenv("DATA_PATH")
  script_path: !expr Sys.getenv("SCRIPT_PATH")
  r_path: !expr Sys.getenv("R_PATH")
  executor: "docker"

k8s:
  base_path: !expr Sys.getenv("BASE_PATH")
  data_path: !expr Sys.getenv("DATA_PATH")
  home_path: !expr Sys.getenv("HOME_PATH")
  script_path: !expr Sys.getenv("SCRIPT_PATH")
  r_path: !expr Sys.getenv("R_PATH")
  api_url: !expr Sys.getenv("KUBERNETES_API_URL")
  namespace: !expr Sys.getenv("KUBERNETES_NAMESPACE")
  token: !expr Sys.getenv("KUBERNETES_API_TOKEN")
  shinyproxy_id: !expr Sys.getenv("SHINYPROXY_ID")
  executor: "k8s"

