FROM biodtshiny

ARG JAVA_VERSION=17

RUN apt-get update -qy && \
    apt-get install -qy --no-install-recommends \
        openjdk-$JAVA_VERSION-jre-headless \
        && \
    apt-get clean

ARG BEEHAVE_IMAGE=ghcr.io/biodt/beehave:0.3.4
ARG NETLOGO_VERSION=6.3.0

COPY --from=$BEEHAVE_IMAGE /conda/env/ /conda/env/
COPY --from=$BEEHAVE_IMAGE ["/NetLogo $NETLOGO_VERSION/", "/NetLogo $NETLOGO_VERSION/"]

# Create beehave_Rscript executable
RUN echo "#!/bin/bash\n\
export JAVA_HOME=/usr/lib/jvm/java-$JAVA_VERSION-openjdk-amd64\n\
export NETLOGO_HOME=\"/NetLogo $NETLOGO_VERSION\"\n\
export NETLOGO_VERSION=\"$NETLOGO_VERSION\"\n\
export PROJ_DATA=/conda/env/share/proj\n\
export LC_ALL=C.UTF-8\n\
unset R_HOME\n\
unset R_VERSION\n\
" > /usr/bin/beehave_Rscript && \
    echo '\n\
/conda/env/bin/Rscript "$@"\n\
' >> /usr/bin/beehave_Rscript && \
    chmod a+x /usr/bin/beehave_Rscript
