FROM rocker/verse:4.3.0
RUN apt-get update -y && apt-get install -y  libicu-dev make zlib1g-dev pandoc  make  libcurl4-openssl-dev libssl-dev  zlib1g-dev  libicu-dev make pandoc  make zlib1g-dev  libssl-dev libcurl4-openssl-dev  pandoc  libpng-dev libicu-dev make libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev pandoc  libssl-dev  libicu-dev zlib1g-dev make pandoc libssl-dev libcurl4-openssl-dev  libpng-dev  libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev  git  libicu-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
